name: test_123
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  bloc: ^8.1.4
  shared_preferences: ^2.0.6
  cached_network_image: ^3.3.1
  intl: ^0.18.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^0.8.4+1
  http_parser: ^4.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1  
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
